/** Declaration file generated by dts-gen */
declare module 'cognitive-services' {
    export class academicKnowledge {
        constructor(_ref: any);

        calcHistogram(_ref2: any): any;

        calcHistogramPost(_ref3: any): any;

        evaluate(_ref4: any): any;

        evaluatePost(_ref5: any): any;

        getSimilarity(_ref9: any): any;

        graphSearch(_ref6: any): any;

        interpret(_ref7: any): any;

        interpretPost(_ref8: any): any;

        postSimilarity(_ref10: any): any;

    }

    export class bingAutosuggest {
        constructor(_ref: any);

        suggestions(_ref2: any): any;

    }

    export class bingImageSearch {
        constructor(_ref: any);

        imageInsights(_ref2: any): any;

        search(_ref3: any): any;

        trending(): any;

    }

    export class bingNewsSearch {
        constructor(_ref: any);

        categoryNews(_ref2: any): any;

        search(_ref3: any): any;

        trendingTopics(_ref4: any): any;

    }

    export class bingSpellCheck {
        constructor(_ref: any);

        spellCheck(_ref2: any): any;

    }

    export class bingVideoSearch {
        constructor(_ref: any);

        details(_ref3: any): any;

        search(_ref2: any): any;

        trending(): any;

    }

    export class bingWebSearch {
        constructor(_ref: any);

        search(_ref2: any): any;

    }

    export class computerVision {
        constructor(_ref: any);

        analyzeImage(_ref2: any): any;

        describeImage(_ref3: any): any;

        getHandwrittenTextOperationResult(_ref8: any): any;

        getThumbnail(_ref4: any): any;

        listDomainSpecificModels(): any;

        ocr(_ref5: any): any;

        recognizeDomainSpecificContent(_ref6: any): any;

        recognizeHandwrittenText(_ref9: any): any;

        tagImage(_ref7: any): any;

    }

    export class emotion {
        constructor(_ref: any);

        emotionRecognition(_ref2: any): any;

        emotionRecognitionInVideo(_ref3: any): any;

        emotionRecognitionWithFaceRectangles(_ref4: any): any;

        getRecognitionInVideoOperationResult(_ref5: any): any;

    }

    export class entityLinking {
        constructor(_ref: any);

        linkEntity(_ref2: any): any;

    }

    export class face {
        constructor(_ref: any);

        addAFaceToAFaceList(_ref7: any): any;

        addAPersonFace(_ref13: any): any;

        createAFaceList(_ref8: any): any;

        createAPerson(_ref14: any): any;

        createAPersonGroup(_ref22: any): any;

        deleteAFaceFromAFaceList(_ref9: any): any;

        deleteAFaceList(_ref10: any): any;

        deleteAPerson(_ref15: any): any;

        deleteAPersonFace(_ref16: any): any;

        deleteAPersonGroup(_ref23: any): any;

        detect(_ref2: any): any;

        findSimilar(_ref3: any): any;

        getAFaceList(_ref11: any): any;

        getAPerson(_ref17: any): any;

        getAPersonFace(_ref18: any): any;

        getAPersonGroup(_ref24: any): any;

        getPersonGroupTrainingStatus(_ref25: any): any;

        group(_ref4: any): any;

        identify(_ref5: any): any;

        listFaceLists(): any;

        listPersonGroups(_ref26: any): any;

        listPersonsInAPersonGroup(_ref19: any): any;

        trainPersonGroup(_ref27: any): any;

        updateAFaceList(_ref12: any): any;

        updateAPerson(_ref20: any): any;

        updateAPersonFace(_ref21: any): any;

        updateAPersonGroup(_ref28: any): any;

        verify(_ref6: any): any;

    }

    export class qnaMaker {
        constructor(_ref: any);

        createKnowledgeBase(_ref2: any): any;

        deleteKnowledgeBase(_ref3: any): any;

        downloadKnowledgeBase(_ref4: any): any;

        generateAnswer(_ref5: any): any;

        getAlterations(_ref6: any): any;

        publishKnowledgeBase(_ref7: any): any;

        trainKnowledgeBase(_ref8: any): any;

        updateAlterations(_ref9: any): any;

        updateKnowledgeBase(_ref10: any): any;

    }

    export class recommendations {
        constructor(_ref: any);

        cancelOperation(_ref2: any): any;

        createAModel(_ref4: any): any;

        createBusinessRule(_ref3: any): any;

        createOrTriggerABuild(_ref5: any): any;

        deleteABuild(_ref8: any): any;

        deleteAModel(_ref11: any): any;

        deleteAllBusinessRules(_ref6: any): any;

        deleteAllUsageFiles(_ref7: any): any;

        deleteBusinessRule(_ref9: any): any;

        deleteCatalogItems(_ref10: any): any;

        deleteUsageFile(_ref12: any): any;

        downloadUsageFile(_ref13: any): any;

        getAModelById(_ref23: any): any;

        getAllBatchJobs(_ref14: any): any;

        getAllBuilds(_ref15: any): any;

        getAllBusinessRules(_ref16: any): any;

        getAllCatalogItems(_ref17: any): any;

        getAllModels(): any;

        getBuildById(_ref18: any): any;

        getBuildDataStatistics(_ref19: any): any;

        getBuildMetrics(_ref20: any): any;

        getBusinessRule(_ref21: any): any;

        getItemToItemRecommendations(_ref22: any): any;

        getModelFeatures(_ref24: any): any;

        getOperationStatus(_ref25: any): any;

        getSpecificCatalogItemsBySearchTerm(_ref26: any): any;

        getUsageStatisticsForABuild(_ref27: any): any;

        getUsageStatisticsForAModel(_ref28: any): any;

        getUserToItemRecommendations(_ref29: any): any;

        listUsageFiles(_ref30: any): any;

        startBatchJob(_ref31: any): any;

        updateCatalogItems(_ref32: any): any;

        updateModel(_ref33: any): any;

        uploadACatalogFileToAModel(_ref34: any): any;

        uploadAUsageFileToAModel(_ref36: any): any;

        uploadUsageEvent(_ref35: any): any;

    }

    export class speakerRecognition {
        constructor(_ref: any);

        identificationProfileCreateEnrollment(_ref2: any): any;

        identificationProfileCreateProfile(_ref3: any): any;

        identificationProfileDeleteProfile(_ref4: any): any;

        identificationProfileGet(_ref5: any): any;

        identificationProfileGetAll(): any;

        identificationProfileResetEnrollments(_ref6: any): any;

        listAllSupportedVerificationPhrases(_ref10: any): any;

        speakerRecognitionGetStatus(_ref7: any): any;

        speakerRecognitionIdentification(_ref8: any): any;

        speakerRecognitionVerification(_ref9: any): any;

        verificationProfileCreateEnrollment(_ref11: any): any;

        verificationProfileCreateProfile(_ref12: any): any;

        verificationProfileDeleteProfile(_ref13: any): any;

        verificationProfileGetAllProfiles(): any;

        verificationProfileGetProfile(_ref14: any): any;

        verificationProfileResetEnrollments(_ref15: any): any;

    }

    export class textAnalytics {
        constructor(_ref: any);

        detectLanguage(_ref2: any): any;

        keyPhrases(_ref3: any): any;

        sentiment(_ref4: any): any;

    }

    export class textTranslator {
        constructor(_ref: any);

        addTranslation(_ref8: any): any;

        addTranslationArray(_ref9: any): any;

        breakSentences(_ref10: any): any;

        detect(_ref6: any): any;

        detectArray(_ref7: any): any;

        getLanguageNames(_ref4: any): any;

        getLanguagesForSpeak(): any;

        getLanguagesForTranslate(): any;

        getTranslations(_ref11: any): any;

        getTranslationsArray(_ref12: any): any;

        speak(_ref5: any): any;

        translate(_ref3: any): any;

        translateArray(_ref2: any): any;

    }

    export class video {
        constructor(_ref: any);

        faceDetectionAndTracking(_ref2: any): any;

        getOperationResult(_ref3: any): any;

        getResultVideo(_ref4: any): any;

        motionDetection(_ref5: any): any;

        stabilization(_ref6: any): any;

        thumbnail(_ref7: any): any;

    }

    export class webLanguageModel {
        constructor(_ref: any);

        breakIntoWords(_ref2: any): any;

        calculateConditionalProbability(_ref3: any): any;

        calculateJointProbability(_ref4: any): any;

        generateNextWords(_ref5: any): any;

        listAvailableModels(): any;

    }

    export namespace academicKnowledge {
        namespace prototype {
            function calcHistogram(_ref2: any): any;

            function calcHistogramPost(_ref3: any): any;

            function evaluate(_ref4: any): any;

            function evaluatePost(_ref5: any): any;

            function getOperationIdFromUrl(url: any): any;

            function getSimilarity(_ref9: any): any;

            function graphSearch(_ref6: any): any;

            function interpret(_ref7: any): any;

            function interpretPost(_ref8: any): any;

            function makeRequest(...args: any[]): any;

            function postSimilarity(_ref10: any): any;

            namespace calcHistogram {
                const prototype: {
                };

            }

            namespace calcHistogramPost {
                const prototype: {
                };

            }

            namespace evaluate {
                const prototype: {
                };

            }

            namespace evaluatePost {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace getSimilarity {
                const prototype: {
                };

            }

            namespace graphSearch {
                const prototype: {
                };

            }

            namespace interpret {
                const prototype: {
                };

            }

            namespace interpretPost {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace postSimilarity {
                const prototype: {
                };

            }

        }

    }

    export namespace bingAutosuggest {
        namespace prototype {
            function getOperationIdFromUrl(url: any): any;

            function makeRequest(...args: any[]): any;

            function suggestions(_ref2: any): any;

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace suggestions {
                const prototype: {
                };

            }

        }

    }

    export namespace bingImageSearch {
        namespace prototype {
            function getOperationIdFromUrl(url: any): any;

            function imageInsights(_ref2: any): any;

            function makeRequest(...args: any[]): any;

            function search(_ref3: any): any;

            function trending(): any;

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace imageInsights {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace search {
                const prototype: {
                };

            }

            namespace trending {
                const prototype: {
                };

            }

        }

    }

    export namespace bingNewsSearch {
        namespace prototype {
            function categoryNews(_ref2: any): any;

            function getOperationIdFromUrl(url: any): any;

            function makeRequest(...args: any[]): any;

            function search(_ref3: any): any;

            function trendingTopics(_ref4: any): any;

            namespace categoryNews {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace search {
                const prototype: {
                };

            }

            namespace trendingTopics {
                const prototype: {
                };

            }

        }

    }

    export namespace bingSpellCheck {
        namespace prototype {
            function getOperationIdFromUrl(url: any): any;

            function makeRequest(...args: any[]): any;

            function spellCheck(_ref2: any): any;

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace spellCheck {
                const prototype: {
                };

            }

        }

    }

    export namespace bingVideoSearch {
        namespace prototype {
            function details(_ref3: any): any;

            function getOperationIdFromUrl(url: any): any;

            function makeRequest(...args: any[]): any;

            function search(_ref2: any): any;

            function trending(): any;

            namespace details {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace search {
                const prototype: {
                };

            }

            namespace trending {
                const prototype: {
                };

            }

        }

    }

    export namespace bingWebSearch {
        namespace prototype {
            function getOperationIdFromUrl(url: any): any;

            function makeRequest(...args: any[]): any;

            function search(_ref2: any): any;

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace search {
                const prototype: {
                };

            }

        }

    }

    export namespace computerVision {
        namespace prototype {
            function analyzeImage(_ref2: any): any;

            function describeImage(_ref3: any): any;

            function getHandwrittenTextOperationResult(_ref8: any): any;

            function getOperationIdFromUrl(url: any): any;

            function getThumbnail(_ref4: any): any;

            function listDomainSpecificModels(): any;

            function makeRequest(...args: any[]): any;

            function ocr(_ref5: any): any;

            function recognizeDomainSpecificContent(_ref6: any): any;

            function recognizeHandwrittenText(_ref9: any): any;

            function tagImage(_ref7: any): any;

            namespace analyzeImage {
                const prototype: {
                };

            }

            namespace describeImage {
                const prototype: {
                };

            }

            namespace getHandwrittenTextOperationResult {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace getThumbnail {
                const prototype: {
                };

            }

            namespace listDomainSpecificModels {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace ocr {
                const prototype: {
                };

            }

            namespace recognizeDomainSpecificContent {
                const prototype: {
                };

            }

            namespace recognizeHandwrittenText {
                const prototype: {
                };

            }

            namespace tagImage {
                const prototype: {
                };

            }

        }

    }

    export namespace emotion {
        namespace prototype {
            function emotionRecognition(_ref2: any): any;

            function emotionRecognitionInVideo(_ref3: any): any;

            function emotionRecognitionWithFaceRectangles(_ref4: any): any;

            function getOperationIdFromUrl(url: any): any;

            function getRecognitionInVideoOperationResult(_ref5: any): any;

            function makeRequest(...args: any[]): any;

            namespace emotionRecognition {
                const prototype: {
                };

            }

            namespace emotionRecognitionInVideo {
                const prototype: {
                };

            }

            namespace emotionRecognitionWithFaceRectangles {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace getRecognitionInVideoOperationResult {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

        }

    }

    export namespace entityLinking {
        namespace prototype {
            function getOperationIdFromUrl(url: any): any;

            function linkEntity(_ref2: any): any;

            function makeRequest(...args: any[]): any;

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace linkEntity {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

        }

    }

    export namespace face {
        namespace prototype {
            function addAFaceToAFaceList(_ref7: any): any;

            function addAPersonFace(_ref13: any): any;

            function createAFaceList(_ref8: any): any;

            function createAPerson(_ref14: any): any;

            function createAPersonGroup(_ref22: any): any;

            function deleteAFaceFromAFaceList(_ref9: any): any;

            function deleteAFaceList(_ref10: any): any;

            function deleteAPerson(_ref15: any): any;

            function deleteAPersonFace(_ref16: any): any;

            function deleteAPersonGroup(_ref23: any): any;

            function detect(_ref2: any): any;

            function findSimilar(_ref3: any): any;

            function getAFaceList(_ref11: any): any;

            function getAPerson(_ref17: any): any;

            function getAPersonFace(_ref18: any): any;

            function getAPersonGroup(_ref24: any): any;

            function getOperationIdFromUrl(url: any): any;

            function getPersonGroupTrainingStatus(_ref25: any): any;

            function group(_ref4: any): any;

            function identify(_ref5: any): any;

            function listFaceLists(): any;

            function listPersonGroups(_ref26: any): any;

            function listPersonsInAPersonGroup(_ref19: any): any;

            function makeRequest(...args: any[]): any;

            function trainPersonGroup(_ref27: any): any;

            function updateAFaceList(_ref12: any): any;

            function updateAPerson(_ref20: any): any;

            function updateAPersonFace(_ref21: any): any;

            function updateAPersonGroup(_ref28: any): any;

            function verify(_ref6: any): any;

            namespace addAFaceToAFaceList {
                const prototype: {
                };

            }

            namespace addAPersonFace {
                const prototype: {
                };

            }

            namespace createAFaceList {
                const prototype: {
                };

            }

            namespace createAPerson {
                const prototype: {
                };

            }

            namespace createAPersonGroup {
                const prototype: {
                };

            }

            namespace deleteAFaceFromAFaceList {
                const prototype: {
                };

            }

            namespace deleteAFaceList {
                const prototype: {
                };

            }

            namespace deleteAPerson {
                const prototype: {
                };

            }

            namespace deleteAPersonFace {
                const prototype: {
                };

            }

            namespace deleteAPersonGroup {
                const prototype: {
                };

            }

            namespace detect {
                const prototype: {
                };

            }

            namespace findSimilar {
                const prototype: {
                };

            }

            namespace getAFaceList {
                const prototype: {
                };

            }

            namespace getAPerson {
                const prototype: {
                };

            }

            namespace getAPersonFace {
                const prototype: {
                };

            }

            namespace getAPersonGroup {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace getPersonGroupTrainingStatus {
                const prototype: {
                };

            }

            namespace group {
                const prototype: {
                };

            }

            namespace identify {
                const prototype: {
                };

            }

            namespace listFaceLists {
                const prototype: {
                };

            }

            namespace listPersonGroups {
                const prototype: {
                };

            }

            namespace listPersonsInAPersonGroup {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace trainPersonGroup {
                const prototype: {
                };

            }

            namespace updateAFaceList {
                const prototype: {
                };

            }

            namespace updateAPerson {
                const prototype: {
                };

            }

            namespace updateAPersonFace {
                const prototype: {
                };

            }

            namespace updateAPersonGroup {
                const prototype: {
                };

            }

            namespace verify {
                const prototype: {
                };

            }

        }

    }

    export namespace qnaMaker {
        namespace prototype {
            function createKnowledgeBase(_ref2: any): any;

            function deleteKnowledgeBase(_ref3: any): any;

            function downloadKnowledgeBase(_ref4: any): any;

            function generateAnswer(_ref5: any): any;

            function getAlterations(_ref6: any): any;

            function getOperationIdFromUrl(url: any): any;

            function makeRequest(...args: any[]): any;

            function publishKnowledgeBase(_ref7: any): any;

            function trainKnowledgeBase(_ref8: any): any;

            function updateAlterations(_ref9: any): any;

            function updateKnowledgeBase(_ref10: any): any;

            namespace createKnowledgeBase {
                const prototype: {
                };

            }

            namespace deleteKnowledgeBase {
                const prototype: {
                };

            }

            namespace downloadKnowledgeBase {
                const prototype: {
                };

            }

            namespace generateAnswer {
                const prototype: {
                };

            }

            namespace getAlterations {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace publishKnowledgeBase {
                const prototype: {
                };

            }

            namespace trainKnowledgeBase {
                const prototype: {
                };

            }

            namespace updateAlterations {
                const prototype: {
                };

            }

            namespace updateKnowledgeBase {
                const prototype: {
                };

            }

        }

    }

    export namespace recommendations {
        namespace prototype {
            function cancelOperation(_ref2: any): any;

            function createAModel(_ref4: any): any;

            function createBusinessRule(_ref3: any): any;

            function createOrTriggerABuild(_ref5: any): any;

            function deleteABuild(_ref8: any): any;

            function deleteAModel(_ref11: any): any;

            function deleteAllBusinessRules(_ref6: any): any;

            function deleteAllUsageFiles(_ref7: any): any;

            function deleteBusinessRule(_ref9: any): any;

            function deleteCatalogItems(_ref10: any): any;

            function deleteUsageFile(_ref12: any): any;

            function downloadUsageFile(_ref13: any): any;

            function getAModelById(_ref23: any): any;

            function getAllBatchJobs(_ref14: any): any;

            function getAllBuilds(_ref15: any): any;

            function getAllBusinessRules(_ref16: any): any;

            function getAllCatalogItems(_ref17: any): any;

            function getAllModels(): any;

            function getBuildById(_ref18: any): any;

            function getBuildDataStatistics(_ref19: any): any;

            function getBuildMetrics(_ref20: any): any;

            function getBusinessRule(_ref21: any): any;

            function getItemToItemRecommendations(_ref22: any): any;

            function getModelFeatures(_ref24: any): any;

            function getOperationIdFromUrl(url: any): any;

            function getOperationStatus(_ref25: any): any;

            function getSpecificCatalogItemsBySearchTerm(_ref26: any): any;

            function getUsageStatisticsForABuild(_ref27: any): any;

            function getUsageStatisticsForAModel(_ref28: any): any;

            function getUserToItemRecommendations(_ref29: any): any;

            function listUsageFiles(_ref30: any): any;

            function makeRequest(...args: any[]): any;

            function startBatchJob(_ref31: any): any;

            function updateCatalogItems(_ref32: any): any;

            function updateModel(_ref33: any): any;

            function uploadACatalogFileToAModel(_ref34: any): any;

            function uploadAUsageFileToAModel(_ref36: any): any;

            function uploadUsageEvent(_ref35: any): any;

            namespace cancelOperation {
                const prototype: {
                };

            }

            namespace createAModel {
                const prototype: {
                };

            }

            namespace createBusinessRule {
                const prototype: {
                };

            }

            namespace createOrTriggerABuild {
                const prototype: {
                };

            }

            namespace deleteABuild {
                const prototype: {
                };

            }

            namespace deleteAModel {
                const prototype: {
                };

            }

            namespace deleteAllBusinessRules {
                const prototype: {
                };

            }

            namespace deleteAllUsageFiles {
                const prototype: {
                };

            }

            namespace deleteBusinessRule {
                const prototype: {
                };

            }

            namespace deleteCatalogItems {
                const prototype: {
                };

            }

            namespace deleteUsageFile {
                const prototype: {
                };

            }

            namespace downloadUsageFile {
                const prototype: {
                };

            }

            namespace getAModelById {
                const prototype: {
                };

            }

            namespace getAllBatchJobs {
                const prototype: {
                };

            }

            namespace getAllBuilds {
                const prototype: {
                };

            }

            namespace getAllBusinessRules {
                const prototype: {
                };

            }

            namespace getAllCatalogItems {
                const prototype: {
                };

            }

            namespace getAllModels {
                const prototype: {
                };

            }

            namespace getBuildById {
                const prototype: {
                };

            }

            namespace getBuildDataStatistics {
                const prototype: {
                };

            }

            namespace getBuildMetrics {
                const prototype: {
                };

            }

            namespace getBusinessRule {
                const prototype: {
                };

            }

            namespace getItemToItemRecommendations {
                const prototype: {
                };

            }

            namespace getModelFeatures {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace getOperationStatus {
                const prototype: {
                };

            }

            namespace getSpecificCatalogItemsBySearchTerm {
                const prototype: {
                };

            }

            namespace getUsageStatisticsForABuild {
                const prototype: {
                };

            }

            namespace getUsageStatisticsForAModel {
                const prototype: {
                };

            }

            namespace getUserToItemRecommendations {
                const prototype: {
                };

            }

            namespace listUsageFiles {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace startBatchJob {
                const prototype: {
                };

            }

            namespace updateCatalogItems {
                const prototype: {
                };

            }

            namespace updateModel {
                const prototype: {
                };

            }

            namespace uploadACatalogFileToAModel {
                const prototype: {
                };

            }

            namespace uploadAUsageFileToAModel {
                const prototype: {
                };

            }

            namespace uploadUsageEvent {
                const prototype: {
                };

            }

        }

    }

    export namespace speakerRecognition {
        namespace prototype {
            function getOperationIdFromUrl(url: any): any;

            function identificationProfileCreateEnrollment(_ref2: any): any;

            function identificationProfileCreateProfile(_ref3: any): any;

            function identificationProfileDeleteProfile(_ref4: any): any;

            function identificationProfileGet(_ref5: any): any;

            function identificationProfileGetAll(): any;

            function identificationProfileResetEnrollments(_ref6: any): any;

            function listAllSupportedVerificationPhrases(_ref10: any): any;

            function makeRequest(...args: any[]): any;

            function speakerRecognitionGetStatus(_ref7: any): any;

            function speakerRecognitionIdentification(_ref8: any): any;

            function speakerRecognitionVerification(_ref9: any): any;

            function verificationProfileCreateEnrollment(_ref11: any): any;

            function verificationProfileCreateProfile(_ref12: any): any;

            function verificationProfileDeleteProfile(_ref13: any): any;

            function verificationProfileGetAllProfiles(): any;

            function verificationProfileGetProfile(_ref14: any): any;

            function verificationProfileResetEnrollments(_ref15: any): any;

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace identificationProfileCreateEnrollment {
                const prototype: {
                };

            }

            namespace identificationProfileCreateProfile {
                const prototype: {
                };

            }

            namespace identificationProfileDeleteProfile {
                const prototype: {
                };

            }

            namespace identificationProfileGet {
                const prototype: {
                };

            }

            namespace identificationProfileGetAll {
                const prototype: {
                };

            }

            namespace identificationProfileResetEnrollments {
                const prototype: {
                };

            }

            namespace listAllSupportedVerificationPhrases {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace speakerRecognitionGetStatus {
                const prototype: {
                };

            }

            namespace speakerRecognitionIdentification {
                const prototype: {
                };

            }

            namespace speakerRecognitionVerification {
                const prototype: {
                };

            }

            namespace verificationProfileCreateEnrollment {
                const prototype: {
                };

            }

            namespace verificationProfileCreateProfile {
                const prototype: {
                };

            }

            namespace verificationProfileDeleteProfile {
                const prototype: {
                };

            }

            namespace verificationProfileGetAllProfiles {
                const prototype: {
                };

            }

            namespace verificationProfileGetProfile {
                const prototype: {
                };

            }

            namespace verificationProfileResetEnrollments {
                const prototype: {
                };

            }

        }

    }

    export namespace textAnalytics {
        namespace prototype {
            function detectLanguage(_ref2: any): any;

            function getOperationIdFromUrl(url: any): any;

            function keyPhrases(_ref3: any): any;

            function makeRequest(...args: any[]): any;

            function sentiment(_ref4: any): any;

            namespace detectLanguage {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace keyPhrases {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace sentiment {
                const prototype: {
                };

            }

        }

    }

    export namespace textTranslator {
        namespace prototype {
            function addTranslation(_ref8: any): any;

            function addTranslationArray(_ref9: any): any;

            function breakSentences(_ref10: any): any;

            function detect(_ref6: any): any;

            function detectArray(_ref7: any): any;

            function getLanguageNames(_ref4: any): any;

            function getLanguagesForSpeak(): any;

            function getLanguagesForTranslate(): any;

            function getOperationIdFromUrl(url: any): any;

            function getTranslations(_ref11: any): any;

            function getTranslationsArray(_ref12: any): any;

            function makeRequest(...args: any[]): any;

            function speak(_ref5: any): any;

            function translate(_ref3: any): any;

            function translateArray(_ref2: any): any;

            namespace addTranslation {
                const prototype: {
                };

            }

            namespace addTranslationArray {
                const prototype: {
                };

            }

            namespace breakSentences {
                const prototype: {
                };

            }

            namespace detect {
                const prototype: {
                };

            }

            namespace detectArray {
                const prototype: {
                };

            }

            namespace getLanguageNames {
                const prototype: {
                };

            }

            namespace getLanguagesForSpeak {
                const prototype: {
                };

            }

            namespace getLanguagesForTranslate {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace getTranslations {
                const prototype: {
                };

            }

            namespace getTranslationsArray {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace speak {
                const prototype: {
                };

            }

            namespace translate {
                const prototype: {
                };

            }

            namespace translateArray {
                const prototype: {
                };

            }

        }

    }

    export namespace video {
        namespace prototype {
            function faceDetectionAndTracking(_ref2: any): any;

            function getOperationIdFromUrl(url: any): any;

            function getOperationResult(_ref3: any): any;

            function getResultVideo(_ref4: any): any;

            function makeRequest(...args: any[]): any;

            function motionDetection(_ref5: any): any;

            function stabilization(_ref6: any): any;

            function thumbnail(_ref7: any): any;

            namespace faceDetectionAndTracking {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace getOperationResult {
                const prototype: {
                };

            }

            namespace getResultVideo {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

            namespace motionDetection {
                const prototype: {
                };

            }

            namespace stabilization {
                const prototype: {
                };

            }

            namespace thumbnail {
                const prototype: {
                };

            }

        }

    }

    export namespace webLanguageModel {
        namespace prototype {
            function breakIntoWords(_ref2: any): any;

            function calculateConditionalProbability(_ref3: any): any;

            function calculateJointProbability(_ref4: any): any;

            function generateNextWords(_ref5: any): any;

            function getOperationIdFromUrl(url: any): any;

            function listAvailableModels(): any;

            function makeRequest(...args: any[]): any;

            namespace breakIntoWords {
                const prototype: {
                };

            }

            namespace calculateConditionalProbability {
                const prototype: {
                };

            }

            namespace calculateJointProbability {
                const prototype: {
                };

            }

            namespace generateNextWords {
                const prototype: {
                };

            }

            namespace getOperationIdFromUrl {
                const prototype: {
                };

            }

            namespace listAvailableModels {
                const prototype: {
                };

            }

            namespace makeRequest {
                const prototype: {
                };

            }

        }

    }

}